### ISSUE TITLE
cross platform i3

### ISSUE THREAD

**Issue by mklabs** [mklabs/todo#13]
- nodejs
- should be able to parse and understand i3 config.
- windows 10 / osx captain

---
- [ ] ~/.config/i3/config parser
- [ ] i3blocks with a node package
- [ ] win10, highly configurable mappings etc. well integrated into native tiling features (which is quite good)
- [ ] osx ... missing xp in osx dev, and didnt have the chance to test captain yet.

**Comment by mklabs** [comment]
cc @alexbooker

**Comment by bookercodes** [comment]
Sounds like a plan :+1:

I've never tried interoperating with the Windows API using Node. I wonder how straightforward it is... :confused:

**Comment by mklabs** [comment]
great!

**Comment by bookercodes** [comment]
To be clear, I didn't mean that **I'm** going to do this. I just think it's a cool idea.

**Comment by mklabs** [comment]
doh ...

**Comment by mklabs** [comment]
I did something similar with tabtab, at least it sounds similar. basically relying on stdout and a spawned node. Not the best, but it's kinda easy to setup.

I higly recommend checking out @lukesampson repos, there's a lot to learn from.
